name: Activate a Revision of an API in Azure API Management

on:
  workflow_dispatch:
    inputs:
      revision:
        description: 'The API revision number to activate'
        required: true
        default: '1'
      api-id:
        description: 'The API to operation against'
        required: true
        default: 'hello-api'

env:
  AZURE_APIM_RG: 'poc-apim-rg'                  # set this to your API Management resource group name on Azure
  AZURE_APIM_NAME: 'pocapi-apim'                # set this to your API Management service name on Azure

permissions:
  id-token: write
  contents: read

jobs:
  activate:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Activate the revision'
      uses: Azure/cli@v1
      env:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        rg: ${{ env.AZURE_APIM_RG }}
        serviceName: ${{ env.AZURE_APIM_NAME }}
        apiId: ${{ inputs.api-id }}
        revision: ${{ inputs.revision }}
      with:
        azcliversion: latest
        inlineScript: |
          # Set variables for your API Management service
          az rest --method patch --uri "https://management.azure.com/subscriptions/$subscriptionId/resourceGroups/$rg/providers/Microsoft.ApiManagement/service/$serviceName/apis/$apiId;rev=$revision?api-version=2021-04-01-preview" --body '{ "properties": { "isCurrent": true } }'
